### ISSUE TITLE
allometry modified data needed

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_TreeRingNPP#10]
Missing data table:
Table3_GTR-NE-319.v2_RossAdendum4.csv

Hi @alexanderm10 - please add this to iPlant when you get a chance or shoot me an email and I will.

I notice that the code calls for the scripts to be in one place 
setwd("/Users/mrossalexander/PhD/Carbon\ Research/pecan/modules/allometry/R")
....and then calls the database from a different place
parm.path <- "~/PhD/Carbon Research/Tree-Rings-and-Biomass/Full_biomass_analysis/raw input files/Table3_GTR-NE-319.v2_RossAdendum4.csv"

I think it makes sense to mirror the PECAN Allometry structure for this particular section.

https://github.com/PecanProject/pecan/tree/master/modules/allometry

This would mean that the NPP analysis would have the following folders  
/allometry
/allometry/R
/allometry/data

Files:
/allometry/R/AllomAve.R
/allometry/R/query.allom.data.R
/allometry/R/allom.BayesFit.R
/allometry/R/read.allom.data.R

/allometry/data/Table3_GTR-NE-319.v2_RossAdendum4.csv

**Comment by alexanderm10** [comment]
All of the files need should be in with the Pecan code. The ...RossAdendum4.csv file is a file that I modified from Dr. Chojnacky's data that he would not like passed around.  The base Jenkins database that is in the Pecan scripts should work just fine as long as you're not working with PIPO samples.

**Comment by davidjpmoore** [comment]
ok
