### ISSUE TITLE
Allometry path to Ross_allometries needs updating

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_TreeRingNPP#11]
line 72 4b_allometry_sampling.R

  loading in BEPA pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.BEPA.2.Rdata")

line 79
  loading in early.hardwood pecan mcmc runs
load(file.path(allom.base, "Allom.BEPA.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.early.hardwood.2.Rdata")

line 86
  loading in FAGR pecan mcmc runs
load(file.path(allom.base, "Allom.BEPA.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.BEPA.2.Rdata")

line 93
  loading in FRAM pecan mcmc runs
load(file.path(allom.base, "Allom.BEPA.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.BEPA.2.Rdata")

line 100
  loading in late.con pecan mcmc runs
load(file.path(allom.base, "Allom.late.con.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.late.con.2.Rdata")

line 107
  loading in late.hardwood pecan mcmc runs
load(file.path(allom.base, "Allom.late.hardwood.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.late.hardwood.2.Rdata")

line 114
  loading in LITU pecan mcmc runs
load(file.path(allom.base, "Allom.LITU.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.LITU.2.Rdata")

line 121
  loading in mid.con pecan mcmc runs
load(file.path(allom.base, "Allom.mid.con.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.mid.con.2.Rdata")

line 128
  loading in north.mid.hardwood pecan mcmc runs
load(file.path(allom.base, "Allom.n.mid.hardwood.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.n.mid.hardwood.2.Rdata")

line 135
  loading in n.pine pecan mcmc runs
load(file.path(allom.base, "Allom.n.pine.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.n.pine.2.Rdata")

line 142
  loading in NYSY pecan mcmc runs
load(file.path(allom.base, "Allom.NYSY.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.NYSY.2.Rdata")

line 149
  loading in PIST pecan mcmc runs
load(file.path(allom.base, "Allom.PIST.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.PIST.2.Rdata")

line 156
  loading in POGR pecan mcmc runs
load(file.path(allom.base, "Allom.POGR.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.POGR.2.Rdata")

line 163
  loading in POTR pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.POTR.2.Rdata")

  line 170
 loading in QUAL pecan mcmc runs
load(file.path(allom.base, "Allom.POTR.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.QUAL.2.Rdata")

  line  177
loading in QURU pecan mcmc runs
load(file.path(allom.base, "Allom.QURU.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.QURU.2.Rdata")

  line 184
loading in QUVE pecan mcmc runs
load(file.path(allom.base, "Allom.QUVE.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.QURU.2.Rdata")

  line 191
loading in so.mid.hardwood pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata")
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.s.mid.hardwood.2.Rdata")

  line 198
 loading in southern pine pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.s.pine.2.Rdata")

  line 205
loading in SAAL pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.SAAL.2.Rdata")

  line 212
loading in TIAM pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.TIAM.2.Rdata")

File and/or path needs to be updated and Allom.XXXXX.Rdata files need to be added to github
@alexanderm10 could you send me the file required here or upload to github /allometries folder ?

**Comment by alexanderm10** [comment]
You need to generate these files from PEcAN before you try to call them.  Since PEcAn has it's own repository (I think we included a link to it in the commit; if not: https://github.com/PecanProject.  You will need to pull the code from here and run script 4a.  Remember to change the input file that PEcAn is reading to be the stock file from the PEcAn repository, as I have modified my file to include collaborator's equations that they wished to remain private.  I know that Mike and Dr. Chojnacky were talking about getting the newer database incorporated into the PEcAn framework.

**Comment by davidjpmoore** [comment]
I've pulled the files and added them to github. 
I just don't have the custom allometry file. 

I'll go ahead and UPDATE the file paths to streamline the code.

**Comment by davidjpmoore** [comment]
I'm not clear on the structure of these code sections:
loading in BEPA pecan mcmc runs
load(file.path(allom.base, "Allom.PINUS.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.BEPA.2.Rdata")

The comment refers to BEPA and then the load commands load PINUS and BEPA ... this pattern is repeated throughout. I was just confused.

**Comment by alexanderm10** [comment]
What this section of code is doing is pulling out a number of random runs from the pecan generated .Rdata file.  These .Rdata files will need to be generated from the PEcAn allometry module and then you get to pick where they are housed.  In my case it was housed in /Ross_allometries with /Allom.SPECIESNAME.2.RDATA being the specific file that the sampling code goes and finds.  The species names in both paths should align, but it seems like I have made some errors here.  Sorry about that.  I will fix it.

**Comment by crollinson** [comment]
As per #16, I think I updated some of the other problems with file paths here (commit bf64e9a8eb2e85e93c67a0f5890ea39d993f36fe).  It's all soft-coded so that if you navigate to where the script is and open it from there, the relative location of things should be okay

**Comment by davidjpmoore** [comment]
@alexanderm10 
is this closed/fixed ?
