### ISSUE TITLE
QURU allometry read in twice

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_TreeRingNPP#12]
starting line 177 in 4b_allometry_sampling.R

QURU is loaded from Ross_allometries in the code below. I'm not sure if it actually does anything but I think it might be an error?
# loading in QURU pecan mcmc runs

load(file.path(allom.base, "Allom.QURU.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.QURU.2.Rdata")
allometries[["QURU"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$QURU)
# loading in QUVE pecan mcmc runs

load(file.path(allom.base, "Allom.QUVE.2.Rdata"))
load("/Users/mrossalexander/Desktop/PEcAn_Allometries/Ross_allometries/Allom.QURU.2.Rdata")
allometries[["QUVE"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$QUVE)

**Comment by alexanderm10** [comment]
The allometry files must be created from the PEcAN scripts first, then they are housed wherever you want.  These files are then called and sampled randomly to make a new object "allometries" which can then be used in the biomass calculations

**Comment by davidjpmoore** [comment]
Thanks - this issue is just about the repeated reference to QURU in the QUVE section of code. I'm not sure if it's a problem but it might require a comment or correction.
