### ISSUE TITLE
lines 113-114 of 2_gapfilling: creating an empty data set

### ISSUE THREAD

**Issue by vlscaven** [davidjpmoore/Calloc_TreeRingNPP#17]
tree.data3 is currently being created as an empty dataset

@alexanderm10 @crollinson

**Comment by alexanderm10** [comment]
So branching off of the uncertainty repository should clear up the tree.data3 issues we were having.

Ross

**Comment by vlscaven** [comment]
Anyone know how I can pull a different branch of the repository into R Studio? I can only get the master branch to show up, even when I fork from the Uncertainty_MS
@alexanderm10 @crollinson @davidjpmoore
