### ISSUE TITLE
error in 0_gapfill_gamm_function

### ISSUE THREAD

**Issue by vlscaven** [davidjpmoore/Calloc_TreeRingNPP#18]
Cannot find object "canopy" at line 40 in gapfill gamm function of Uncertainty_MS
@alexanderm10 @crollinson @davidjpmoore

**Comment by crollinson** [comment]
@vlscaven It would really help if you could paste the _exact_ error message from R plus summary/header of the object it's looking for things in (i.e. whatever's in the data= statement).  Knowing what was the last line to run without errors would also really help isolate where in the scripts things broke.

The things you tend to create github issues for are what frequently result from a either change in name in input file that didn't get updated (capitalization is a pain!) or something not getting read in properly.  The scripts are a hodgepodge of what Ross & I have learned over the years, so there are definitely a few kinks that we smoothed over later that we forgot to update in the early stages. As much context as you can give to help us figure out what _exactly_ is going wrong would really help us diagnose things without making us start from scratch and try to reproduce your error.

I know Ross talked with you a little bit about how to go about debugging things, but maybe it'd be useful for you and I &/or @alexanderm10 to have a Skype chat about how we can help you figure out what were simple mistakes by us that you can fix (i.e. naming, etc) versus a bigger problem that we need to track down (i.e. problem with raw data, etc).  Send an email to crollinson <at> gmail <dot> com and we can set up a time that works for you.

**Comment by davidjpmoore** [comment]
@crollinson @alexanderm10 - this issue was a problem with the way that we pulled from git. @vlscaven now has a new local branch and will discover new issues later ... skype would be very useful!
