### ISSUE TITLE
cannot find function rmvnorm in 4a_query_allometry_script

### ISSUE THREAD

**Issue by vlscaven** [davidjpmoore/Calloc_TreeRingNPP#19]
When I run the "Generating Allometries" section of the code (lines 23-102) it seems to run but gives me this error message at the end of every 5 or 10 lines: 

Error in t(rmvnorm(1, bigV %*% littlev, bigV)) : 
  could not find function "rmvnorm" 
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘coda’
2: In nu(allom$parm$Component.ID) : NAs introduced by coercion
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘mvtnorm’
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘MCMCpack’

@alexanderm10 @crollinson @davidjpmoore

**Comment by vlscaven** [comment]
I tried downloading these packages from CRAN but R still cannot find them in the library

**Comment by crollinson** [comment]
did you download Pecan and set the paths appropriately?

**Comment by crollinson** [comment]
So what's going on is something with Pecan or the libraries... those errors are showing up every time you're trying to run the AllomAve script.  If you double check pecan & its paths and are still getting errors, we'll find a way to get you the version of the scripts Ross & I have been using
