### ISSUE TITLE
file names rethink

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_TreeRingNPP#6]
We need to standardize the file names for these analyses:

The code lists the following file:
'raw input files/tree_metadata_DOE_plus_valles.csv'

I'm assuming this is the same file as 'DOE_plus_valles.csv'

Recommend making file name reflect the type of file it is. 

For the Carbon Allocation Project (DOE) - let's go with "Calloc" rather than DOE to avoid confusion with other DOE projects.
Something like PROJECT_Meta.csv or PROJECT.metacsv

**If we modify the FILE EXTENSION - we can then move to a generic file reading approach, we should still be able to use read.csv
for example:

tempFilelist = list.files(filepath,pattern="*.csv")
# read all the *.csv files in the working directory

tempFilelist = list.files(filepath,pattern="*.csv")
# get the AmeriFlux files information (site and years)

files<-substr(tempFilelist,7,14)
# get the AmeriFlux site code

site<-substr(tempFilelist[1],7,9)
# get the data and header from the L2 files

myfiles = do.call("rbind", lapply(paste0(filepath,tempFilelist), function(x) read.csv(x, skip=20,header=FALSE,stringsAsFactors = FALSE)))

AmFluxheader=read.csv(tempFilelist[1],skip=17, strip.white=TRUE, nrows=1 ,header=FALSE,stringsAsFactors=FALSE)

colnames(myfiles)<-AmFluxheader

**Comment by alexanderm10** [comment]
Dave I forgot to upload one file.  I added the tree_metadata_DOE_plus_vales.csv to the iPlant.  Things should work now.

**Comment by davidjpmoore** [comment]
ok
